apiVersion: batch/v1
kind: Job
metadata:
  name: tester-consumers
spec:
  parallelism: 12
  completions: 12
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
            - "./rabbit-mq-stress-tester"
            - "--server"
            - "rabbit-ha-postventa-stress-rabbitmq-ha.default"
            - "--vhost"
            - "stressing"
            - "--port"
            - "5672"
            - "--user"
            - "stress"
            - "--password"
            - "rompePepe83"
            - "--consumer"
            - "0"
            - "--concurrency"
            - "4"
            - "--exchange"
            - "stress-test-ex-delayed2"
            - "--delay-messages"
            - "60000"
        image: registry.gitlab.com/fravega/arquitectura/rabbit-mq-stress-tester:1.3.2
        imagePullPolicy: Always
        name: tester
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "16Mi"
            cpu: "50m"
      restartPolicy: Never
      imagePullSecrets:
      - name: gitlab-regcred
