apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: tester
  name: tester
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tester
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tester
    spec:
      containers:
      - args:
        - /bin/bash
        image: docker-registry.cluster.fravega.com/fravega/rabbit-mq-stress-tester:master-eee9c62
        imagePullPolicy: Always
        name: tester
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      imagePullSecrets:
      - name: nexus-registry
