apiVersion: batch/v1
kind: Job
metadata:
  name: tester-producers-postventa-stress
  namespace: default
spec:
  parallelism: 10
  completions: 10
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
            - "./rabbit-mq-stress-tester"
            - "--server"
            - "rabbit-ha-postventa-stress-rabbitmq-ha-discovery.default"
            - "--vhost"
            - "stressing"
            - "--port"
            - "5672"
            - "--user"
            - "stress"
            - "--password"
            - "rompePepe83"
            - "--producer"
            - "1000"
            - "--exchange"
            - ""
            - "--bytes"
            - "4096"
            - "--concurrency"
            - "5"
            - "--wait-for-ack"
        image: docker-registry.management.fravega.com/fravega/rabbit-mq-stress-tester:1.2.3
        imagePullPolicy: Always
        name: tester
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"
      restartPolicy: Never
      imagePullSecrets:
      - name: nexus
